application:
  swagger:
    enabled: true
    regexPathExclusion: (/actuator.*|/error.*)
    version: @project.version@
    title: @project.name@
    description: Swagger documentation for @project.description@
    license:
    contact:
      name: Virtual Wallet Team
      email: NOREFUNDS@wallet.bbd
spring:
  servlet:
    multipart:
      location: ${user.dir}
  h2:
    console:
      enabled: true
  datasource:
    platform: mysql
    data: classpath:data-mysql.sql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_wallet?sslMode=DISABLED
    username: root
    password: root

  jpa:
    hibernate.ddl-auto:
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  batch:
    initialize-schema: always
flyway:
  url: jdbc:mysql://localhost:3306/mysql
  user: "root"
  password: "root"
  schemas: test_wallet